[project] Create .git/hooks directory, there is no guarantee it exists
I've hit this while trying to bootstrap Fuchsia, it seems protobuf
doesn't have it:

```
$ .jiri_root/bin/jiri update
[13:24:10.850] Updating all projects
ERROR: manifest.go:1358: open /usr/local/google/home/yanok/fuchsia/third_party/protobuf/.git/hooks/commit-msg: no such file or directory
```

Change-Id: Ie4ce4788aaa629bc17d3542f3eee43959fdf3833
Reviewed-on: https://fuchsia-review.googlesource.com/c/jiri/+/613162
Commit-Queue: Ilya Yanok <yanok@google.com>
Reviewed-by: Nathan Mulcahey <nmulcahey@google.com>